--- 
after_failure: 
  - "gdb $(pwd)/test core -ex \"thread apply all bt\" -ex \"set pagination 0\" -batch"
before_script: 
  - "ulimit -c unlimited -S"
dist: bionic
install: 
  - "sudo apt-get install -y gdb"
language: cpp
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: "COMPILER=g++-8 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O0 -g -mavx2 -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
    - 
      addons: 
        apt: 
          packages: 
            - clang-7
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
      compiler: clang
      env: "COMPILER=clang++-7 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O0 -g -mavx2 -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
    - 
      addons: 
        apt: 
          packages: 
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: "COMPILER=g++-8 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O2 -g -mavx2 -mno-avx256-split-unaligned-load -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
    - 
      addons: 
        apt: 
          packages: 
            - clang-7
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
      compiler: clang
      env: "COMPILER=clang++-7 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O3 -g -mavx2 -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
os: linux
script: 
  - "cd ./xxhash"
  - "make CXX=$COMPILER OUTNAME=test0 CMDARGS=\"-DXXH_VECTOR=0\""
  - "make CXX=$COMPILER OUTNAME=test1 CMDARGS=\"-DXXH_VECTOR=1\""
  - "make CXX=$COMPILER OUTNAME=test2 CMDARGS=\"-DXXH_VECTOR=2\""
  - ./test0
  - ./test1
  - ./test2
sudo: required
