--- 
after_failure: 
  - "gdb $(pwd)/test core -ex \"thread apply all bt\" -ex \"set pagination 0\" -batch"
before_script: 
  - "ulimit -c unlimited -S"
dist: bionic
install: 
  - "sudo apt-get install -y gdb"
language: cpp
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: "CC=g++-8"
    - 
      addons: 
        apt: 
          packages: 
            - clang-7
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
      compiler: clang
      env: "CC=clang++-7"
os: linux
script: 
  - make
  - ./test_scalar_debug
  - ./test_scalar_release
  - ./test_sse2_debug
  - ./test_sse2_release
  - ./test_avx2_debug
  - ./test_avx2_release
sudo: required
