--- 
after_failure: 
  - "gdb $(pwd)/test core -ex \"thread apply all bt\" -ex \"set pagination 0\" -batch"
before_script: 
  - "ulimit -c unlimited -S"
dist: bionic
install: 
  - "sudo apt-get install -y gdb"
language: cpp
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-7
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: "COMPILER=g++-7 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O0 -g -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
    - 
      addons: 
        apt: 
          packages: 
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: "COMPILER=g++-8 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O0 -g -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
    - 
      addons: 
        apt: 
          packages: 
            - clang-7
            - g++-8
            - gdb
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
      compiler: clang
      env: "COMPILER=clang++-7 CPPVERFLAG=-std=c++17 EXTRAARGS=\" -O0 -g -march=native -Wall -Wpedantic -Wextra \" LIBS=\"\""
os: linux
script: 
  - "cd ./xxhash"
  - "make CXX=$COMPILER"
  - ./test
sudo: required
